config/routes.rb
Webforum::Application.routes.draw do
  root :to => 'login#log_in'
  
  resources :login do
    member do

    end

    collection do 
      get 'log_in'
      post 'log_in'
      post 'login_process' 
    end
  end

  resources :users do
    member do

    end

    collection do 

    end
  end

  resources :admin do
    member do
    end

    collection do 
      get 'show'
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :account_number
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_content
  belongs_to :post
end

app/models/log_in.rb
class LogIn < ActiveRecord::Base
 attr_accessible :user_name, :password
 belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :post_content
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :age
  has_many :posts
  has_many :comments, :through => :posts
  has_one :account
  has_one :log_in, :dependent => :destroy






end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def show
		@admin_details = User.find_by_id(session[:id])
		@user = User.all
	end

	def index

	end

	def edit
		
	end	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def show
		
	end

	def log_in

	end	

	def index

	end

	def login_process		
			@login = LogIn.find_by_user_name(params['username'])
			if @login
				respond_to do |format|
						if @login.password == params['password']
							flash[:notice] = "log in success.........."
							session[:id] = @login[:user_id]
				  					format.html { redirect_to admin_index_path }
				  					format.json {head :no_content}
						else
							flash[:notice] = "password error.........."	
							redirect_to log_in_login_index_path  

						end
				end
			else
				flash[:notice] = "invalid user..."	
				redirect_to log_in_login_index_path 
			end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user = User.new  
	  @login = LogIn.new
	end

	def create               
	  @user = User.new(params[:user])
	  @login = @user.build_log_in(params[:log_in])
		respond_to do |format|
	  				if @user.save
	  					#render :text => @user.errors.to_yaml and return 
	  					flash[:notice] = "User Information saved"
	  					#redirect_to log_in_login_path 
	  					format.html { redirect_to log_in_login_index_path }
	  					format.json { head :no_content }	  					
	  				else
	  					#render :text => @user.errors.to_yaml and return 
	  					flash[:notice] = "User Information not saved"
	  					format.html {render "new"}
	  				end
		end
	end

    def show
    end

    def destroy
    	@users = User.find(params[:id])
    	@users.destroy
    	redirect_to admin_path
    end

    def edit
    end




end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<html>
  <body style = "margin:0; font-size:17px;">
  	<div style="width:100%; height:130px;  background:#C2C2C2;;margin:0;">
	    <div style="width:1000px; margin:0 auto; height:100px;">
	      <div style="width:300px; float:left;">
	        <%= image_tag("admin.gif", :alt => "test image" ,:style =>"width:200px;") %>
	      </div>
	      <div style="width:300px; float:right; padding-top:40px;margin:0;" align="left">
	           <div style="width:100px;float:left; line-height:20px;">NAME:<br />AGE:</div>
	           <div style="width:100px;float:left; line-height:20px;"><%= @admin_details[:name] %><br />
	           <%= @admin_details[:age]%></div>
	    </div>
    </div>	
	<div style="width:1000px; margin:0 auto; overflow:hidden;">
		  <div style="width:900px; margin:2px auto; overflow:hidden;  background:#C2C2C2;" align="center">
		  		<strong>USERS</strong>
		  </div>

		<% @user.each do |data| %>
		  <div style="width:900px; margin:2px auto; overflow:hidden; background:#C2C2C2;">
			  <div style="float:left"><%= image_tag("", :alt => "test image" ,:style =>"width:50px;height:50px;") %>	
			  </div>
		      <div style="width:300px; float:left; padding-top:40px;margin:0;" align="left">
			  	   <div style="width:100px;float:left; line-height:30px;">NAME:<br />AGE:</div>
		           <div style="width:100px;float:left; line-height:30px;"><%= data.name %><br /><%= data.age %></div>
			  </div>


			  <div style="float:right; padding-top:50px;padding-right:30px;">
				<%= link_to "SHOW",admin_path(data) %>&nbsp&nbsp
			  	<%= link_to "EDIT",new_user_path%>&nbsp&nbsp
				<%= link_to "DELETE",data, :confirm => "are you sure", :method => :delete %>
			  </div>

		  </div>	
		<% end %>
	</div>
  	<div style="width:100%; height:50px;  background:#C2C2C2;;margin:0;">
    </div>	
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webforum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/log_in.html.erb
<html>
<head><title>log in</title></head>
<body>
	<form name = "login" action = <%= login_process_login_index_path %> method = "Post">
	<table align = "right">
		<tr>
			<td colspan="2" align = "center">
				LOG IN
			</td>
		</tr>
		<tr>
			<td>
				USERNAME:
			</td>
			<td>
				<input type="text" name="username" >
			</td>
		</tr>
		<tr>
			<td>
				PASSWORD:
			</td>
			<td>
				<input type="text" name="password" value="">
			</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="log in">
				<%if flash[:notice]%>
                  <%=flash[:notice]%>
                <%end%>                 
			</td>
		</tr>
		<tr>
			<td rowspan="2" align="center">
				<%= link_to "SIGN UP",new_user_path%>
			</td>
		</tr>

	</table>
	</form>
</body>
</html>

app/views/users/new.html.erb
<html>
<head><title>log in</title></head>
<body>


    <%= form_for @user do |f|%>

    <table align="right" width="400px">

        <tr><td colspan="2" align="center">

           
        </td></tr>
    	<tr><td colspan="2" align="center"><h3>SIGN UP</h3></td></tr>
    	<tr>
    		<td>
				<%= f.label :name %>
			</td>
			<td>
				<%= f.text_field :name %>

			</td>
		</tr>

		<tr>
    		<td>
				<%= f.label :age %>
			</td>
			<td>
				<%= f.text_field :age %>
			</td>
		</tr>
    <%= fields_for @login do |login_details_form| %>
		<tr>
    		<td>
				<%= login_details_form.label :user_name %>

			</td>
			<td>
				<%= login_details_form.text_field :user_name %>
			</td>
		</tr>

		<tr>
    		<td>
				<%= login_details_form.label :password %>
			</td>
			<td>
				<%= login_details_form.text_field :password %>
			</td>
		</tr>
    <%end%>
        <tr>
            <td colspan="2" style="color:red; font-size:12px;">
                    
            </td>
        </tr>
		<tr>
			<td colspan="2" align="center" style="color:red; font-size:15px;">
				<%= f.submit "SIGN UP"%><br />
			</td>
		</tr>

	
				<%#= f.label :password_confirm %>
				<%#= f.text_field :password_confirm %>
	</table>

	<% end %>

</body>
</html>